app <- ShinyDriver$new("../../")
app$snapshotInit("test-dashboard")

app$snapshot()
app$setInputs(bandejas_remove_estanteria = "click")
app$snapshot()
app$setInputs(bandejas_add_estanteria = "click")
app$snapshot()
app$setInputs(bandejas_remove_balda = "click")
app$snapshot()
app$setInputs(bandejas_add_balda = "click")
app$snapshot()
app$setInputs(bandejas_remove_bandeja = "click")
app$snapshot()
app$setInputs(bandejas_add_bandeja = "click")
app$snapshot()
app$setInputs(bandejas_add_bandeja = "actualizar")
app$snapshot()

